#!/bin/bash
set -e
src=/opt/odoo/prod/odoo
dst=/usr/local/bin/odoo

log WARNING Blindly symlinking odoo executable to Prod repo
bin=$src/odoo-bin
# Cannot check for scripts existence and link all: they probably do not
# exist yet at build time! Just check Odoo version and act properly.
if [ "$ODOO_VERSION" == "7.0" ]; then
    bin=$src/openerp-server
    ln -s /opt/odoo/custom/src/odoo/openerp-server /usr/local/bin/
elif [ "$ODOO_VERSION" == "8.0" -o "$ODOO_VERSION" == "9.0" ]; then
    bin=$src/odoo.py
    ln -s /opt/odoo/custom/src/odoo/openerp-{gevent,server} /usr/local/bin/
fi
ln -s $bin $dst
